aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml
kubectl proxy
kubectl apply -f kubernetes-dashboard-admin.rbac.yaml
kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep service-controller-token | awk '{print $1}')

#eyJhbGciOiJSUzI1NiIsImtpZCI6Il9rNjJxNkNTMXMyUkN3bU1xakNqZ1NqU0lBT0NNSjludk5kUkJMSlVtdmcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJzZXJ2aWNlLWNvbnRyb2xsZXItdG9rZW4tZzRtdDUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic2VydmljZS1jb250cm9sbGVyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNTQ3YmNmYzUtODE2MC00Yjc4LTk3ZmUtODlkMTc0OTk1YWE4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOnNlcnZpY2UtY29udHJvbGxlciJ9.eG-sftSuPZLFBihHtHK4ZpAzQhZoTtV__EniB3AjMpu99PxGtcAGjGGciq-OiNi9iBK9CmwyCWW0yB9VjVLM0gdYMY6ttn5-1t3xNjRRuTRlx2_PW_utERaOoBniUI5ClL3UXGuyEAHZZe9dnE3aUXlVhD7t2JJ5GphwcNmGCWpUHbVm2W0BaSGcmkYzwqVgEEN4UKAksdRkmHjcCgXCZfRdB9t5lBFIS0or_b1tGqBAmAENeEyKuW2WrunF6cZEIOABHNofxliw8QuKBAgTVTmAX6hBpmPdhB0zX2nqQT-XkPL-lCrqJ00vFLZ0hIBopSMW6b-aK5QcqpI9DLDqMQ
