{{- range .Values.applications}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{.name}}
spec:
  type: {{ .serviceType }}
  ports:
    - port: {{ .containerPort }}
      targetPort: {{.targetPort}}
      protocol: {{.protocol}}
      name: {{.portName}}
  selector:
    app: {{.name}}
{{- end }}
